version: "3.8"
services:
  mysqldb:
    container_name: graphql-database
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD_MYSQL
      MYSQL_DATABASE: $DB_DATABASE_MYSQL
      SERVICES_TAGS: dev
      SERVICES_NAME: mysqldb
    ports:
      - "3306:3306"
    networks:
      - graphqlnet
  app:
    depends_on:
      - mysqldb
    container_name: mysql-graphql-app
    restart: always
    build: .
    env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      - graphqlnet
    stdin_open: true
    tty: true
volumes: 
  db:
networks:
  graphqlnet:
    driver: bridge